version: '3'
services:
  local-db:
    image: rubok/mysql
    container_name: mysql
    restart: always
    ports:
      - 33063:3306
    environment:
      - MYSQL_DATABASE=pcria
      - MYSQL_USER=rubok
      - MYSQL_PASSWORD=master
      - TZ= Asia/Seoul
    volumes:
      - /Users/seokgyuhwan/vscode/dockerfile/mysql/mysql:/var/lib/mysql
      - /Users/seokgyuhwan/vscode/dockerfile/mysql/db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64

  application:
    build: .
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - local-db
    container_name: app_pcria
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://local-db:3306/pcria?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: rubok
      SPRING_DATASOURCE_PASSWORD: master

