spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/pcria?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: master
    #    url: jdbc:mysql://192.168.0.16:3306/pcria?characterEncoding=UTF-8&serverTimezone=UTC
    #    username: rubok
    #    password: 213216
#    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
#    static-path-pattern: /resources/static/**

mybatis:
  type-aliases-package: com.example.pcria.domain
  mapper-locations: mybatis/mapper/**/*.xml

server:
  servlet:
    jsp:
      init-parameters:
        development: true