spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcria?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: master
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
#    static-path-pattern: /res/**

# mybatis alias & mapper 위치 설정
mybatis:
  type-aliases-package: com.example.pcria.domain
  mapper-locations: mybatis/mapper/**/*.xml

# jsp 수정 후 확인할 수 있는 설정
server:
  servlet:
    jsp:
      init-parameters:
        development: true